---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.14.0
  name: tenantprofiles.platform.example.com
spec:
  group: platform.example.com
  names:
    kind: TenantProfile
    listKind: TenantProfileList
    plural: tenantprofiles
    shortNames:
    - tp
    singular: tenantprofile
  scope: Cluster
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            properties:
              limits:
                properties:
                  defaultCpu:
                    pattern: ^([0-9]+m|[0-9]+)$
                    type: string
                  defaultMemory:
                    pattern: ^[0-9]+(Mi|Gi)$
                    type: string
                  maxCpu:
                    pattern: ^([0-9]+m|[0-9]+)$
                    type: string
                  maxMemory:
                    pattern: ^[0-9]+(Mi|Gi)$
                    type: string
                required:
                - defaultCpu
                - defaultMemory
                - maxCpu
                - maxMemory
                type: object
              quota:
                properties:
                  cpu:
                    pattern: ^([0-9]+m|[0-9]+)$
                    type: string
                  memory:
                    pattern: ^[0-9]+(Mi|Gi)$
                    type: string
                  pods:
                    format: int32
                    minimum: 1
                    type: integer
                required:
                - cpu
                - memory
                - pods
                type: object
            required:
            - limits
            - quota
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
