apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespace-operator
rules:
- apiGroups: [""]
  resources:
  - namespaces
  - resourcequotas
  - limitranges
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

- apiGroups: ["platform.example.com"]
  resources:
  - tenants
  - tenants/status
  verbs: ["get", "list", "watch", "update", "patch"]
