apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: namespace-operator
subjects:
- kind: ServiceAccount
  name: namespace-operator-controller-manager
  namespace: namespace-operator-system
roleRef:
  kind: ClusterRole
  name: namespace-operator
  apiGroup: rbac.authorization.k8s.io
