apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "namespace-operator.fullname" . }}
  labels:
{{ include "namespace-operator.labels" . | indent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "namespace-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "namespace-operator.fullname" . }}
  apiGroup: rbac.authorization.k8s.io