apiVersion: v1
kind: Service
metadata:
  name: {{ include "namespace-operator.fullname" . }}
  labels:
    {{- include "namespace-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range .Values.ports }}
    - name: {{ .name }}
      port: {{ $.Values.service.port }}
      targetPort: {{ .name }}
      protocol: {{ .protocol }}
  {{- end }}
  selector:
    {{- include "namespace-operator.selectorLabels" . | nindent 4 }}