name: CI

on:
  push:
    branches: ["main"]
  pull_request:

env:
  GO_VERSION: "1.22"

jobs:
  go-tools:
    name: Go tools
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Prepare PATH
        run: |
          mkdir -p .bin
          echo "$PWD/.bin" >> $GITHUB_PATH

      - name: Install tools
        run: make go


  generate:
    name: Generate
    runs-on: ubuntu-latest
    needs: go-tools

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - run: echo "$PWD/.bin" >> $GITHUB_PATH

      - name: Generate code
        run: make generate

      - name: Upload generated artifacts
        uses: actions/upload-artifact@v4
        with:
          name: generated
          path: |
            api/**/zz_generated.deepcopy.go
            config/crd/bases/*.yaml


  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: generate

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - run: echo "$PWD/.bin" >> $GITHUB_PATH

      - name: Download generated artifacts
        uses: actions/download-artifact@v7
        with:
          name: generated

      - run: make lint


  build:
    name: Build
    runs-on: ubuntu-latest
    needs: generate

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - run: echo "$PWD/.bin" >> $GITHUB_PATH

      - name: Download generated artifacts
        uses: actions/download-artifact@v7
        with:
          name: generated

      - run: make build


  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - run: echo "$PWD/.bin" >> $GITHUB_PATH

      - name: Download generated artifacts
        uses: actions/download-artifact@v7
        with:
          name: generated

      - run: make test