name: Release Docker Image

on:
  push:
    tags:
      - "v*.*.*"

env:
  REGISTRY: docker.io
  IMAGE_NAME: baabdoul/namespace-operator
  GO_VERSION: "1.24"

jobs:
  go-tools:
    name: Go tools
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true
          cache-dependency-path: src/go.sum
      - name: Prepare PATH
        run: |
          mkdir -p ./.bin
          echo "$PWD/.bin" >> $GITHUB_PATH

      - name: Install tools
        run: make install-go


  generate:
    name: Generate
    runs-on: ubuntu-latest
    needs: go-tools

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true
          cache-dependency-path: src/go.sum
      - run: echo "$PWD/.bin" >> $GITHUB_PATH

      - name: Generate code
        run: make generate

      - name: Upload generated artifacts
        uses: actions/upload-artifact@v4
        with:
          name: generated
          path: |
            src/api/**/zz_generated.deepcopy.go
            manifests/charts/namespace-operator/crds/*.yaml


  docker:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: generate

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      # ðŸ”‘ Restore generated files EXACTLY where Go/Docker expects them
      - name: Download generated artifacts
        uses: actions/download-artifact@v7
        with:
          name: generated
          path: .

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract version from tag
        id: meta
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          echo "VERSION=${TAG#v}" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.VERSION }}
            ${{ env.IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max